# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Geography-JapanesePrefectures-Walker
version:      0.01
version_from: lib/Geography/JapanesePrefectures/Walker.pm
installdirs:  site
requires:
    Encode:                        0
    Geography::JapanesePrefectures: 0
    List::MoreUtils:               0
    Scalar::Util:                  0
    Test::Class:                   0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
